### ISSUE TITLE
Double scrollbar issue in firefox

### ISSUE THREAD

**Issue by harp71** [zlsa/atc#380]
There is a height-issue in firefox regarding the airport-selection:

![image](https://cloud.githubusercontent.com/assets/11310456/12874016/f5df9d34-cdcb-11e5-98cf-c2c992ba6a86.png)

It is resolved by changing one parameter in airport.css from 85% to 87% (see below). But i don´t know if this is just a temporary fix for the amount and name-length of the existing airports. So can please somebody double-check this:

``` css
#airport-switch{max-height: calc(87% - 2.3em - 20px);}
```

**Comment by engeplabs** [comment]
No this doesn't fix it. What you are doing is allowing the container (the whole picture you uploaded) to grow big enough to contain the the list of the airports. As more airports are added the two scrollbars appear again.
You have to adress the max-height of the inner frame to make it work permanently...

edit

``` css
#airport-list {  max-height: calc(100% - 2.3em - 32px); }
```

changed `30px` to `32px`

But I dont like this approach because it is pixel painting (or "Pixelmalerei" as we say in german). There must be some other way to solve this problem... I mean: how did the `-30px` get there in the first place?
